name: Documentation CI

on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches: [develop, main]
        paths:
            - "**.md"
            - "docs/**"
            - ".github/PULL_REQUEST_TEMPLATE/**"

permissions:
    contents: read
    pull-requests: write

jobs:
    docs-check:
        name: Documentation Check
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Comment on PR
              uses: actions/github-script@v7
              with:
                  script: |
                      await github.rest.issues.createComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.payload.pull_request.number,
                        body: '✅ Documentation checks passed!\n\nThis PR only changes documentation - no code quality checks needed.'
                      });
